// Job sites plotted on the Projects map. Generated by scratchpad geo.py from a
// curated, evidence-backed list (see SOURCES.md). Coordinates: 2024 US Census
// Gazetteer internal points (place or county). Do not edit by hand.
export type JobSite = { name: string; state: string; stateName: string; lat: number; lon: number; work?: string };
export const hq = { name: 'Knoxville, TN', lat: 35.9707, lon: -83.9493 };
export const jobsites: JobSite[] = [
  { name: "Cleveland", state: 'TN', stateName: 'Tennessee', lat: 35.18, lon: -84.8713 }, // Cleveland city (4715400)
  { name: "Elizabethton", state: 'TN', stateName: 'Tennessee', lat: 36.3396, lon: -82.2378 }, // Elizabethton city (4723500)
  { name: "Greeneville", state: 'TN', stateName: 'Tennessee', lat: 36.168, lon: -82.8197 }, // Greeneville town (4730980)
  { name: "Johnson City", state: 'TN', stateName: 'Tennessee', lat: 36.3423, lon: -82.3809 }, // Johnson City city (4738320)
  { name: "Kingsport", state: 'TN', stateName: 'Tennessee', lat: 36.5194, lon: -82.5434 }, // Kingsport city (4739560)
  { name: "Oak Ridge", state: 'TN', stateName: 'Tennessee', lat: 35.9665, lon: -84.2905 }, // Oak Ridge city (4755120)
  { name: "Monroe", state: 'TN', stateName: 'Tennessee', lat: 35.4478, lon: -84.2497 }, // Monroe County (47123)
  { name: "Linden", state: 'TN', stateName: 'Tennessee', lat: 35.6123, lon: -87.843 }, // Linden town (4742720)
  { name: "Collinwood", state: 'TN', stateName: 'Tennessee', lat: 35.1745, lon: -87.7441 }, // Collinwood city (4716480)
  { name: "Pell City", state: 'AL', stateName: 'Alabama', lat: 33.5603, lon: -86.2636 }, // Pell City city (0158896)
  { name: "Falkville", state: 'AL', stateName: 'Alabama', lat: 34.377, lon: -86.9095 }, // Falkville town (0125648)
  { name: "Bon Secour", state: 'AL', stateName: 'Alabama', lat: 30.3182, lon: -87.7244 }, // Bon Secour CDP (0108272)
  { name: "Grand Bay", state: 'AL', stateName: 'Alabama', lat: 30.4721, lon: -88.3444 }, // Grand Bay CDP (0131024)
  { name: "Foley", state: 'AL', stateName: 'Alabama', lat: 30.3971, lon: -87.6685 }, // Foley city (0126992)
  { name: "Highlands", state: 'NC', stateName: 'North Carolina', lat: 35.0538, lon: -83.1976 }, // Highlands town (3731360)
  { name: "Charlottesville", state: 'VA', stateName: 'Virginia', lat: 38.0377, lon: -78.4854 }, // Charlottesville city (5114968)
];
